export const blockchains = [
  {
    item: "Aeternity",
    slug: "aeternity",
    placeholder: "ak_... address",
    coin: "AE",
    id: "",
    startDate: "2018-12-04",
  },
  {
    item: "Binance",
    slug: "bsc",
    placeholder: "0x... address",
    coin: "BNB",
    id: 56,
    startDate: "2020-09-04",
  },
  {
    item: "Celo",
    slug: "celo",
    placeholder: "0x... address",
    coin: "CELO",
    id: 42220,
    startDate: "2020-05-23",
  },
  {
    item: "Cube",
    slug: "cube",
    placeholder: "0x... address",
    coin: "CUBE",
    id: 1818,
    startDate: "2020-06-06",
  },
  {
    item: "Ethereum",
    slug: "ethereum",
    placeholder: "0x... or .eth",
    coin: "ETH",
    id: 1,
    startDate: "2015-7-30",
  },
  {
    item: "Evmos",
    slug: "evmos",
    placeholder: "0x... address",
    coin: "EVMOS",
    id: 9001,
    startDate: "2022-05-04",
  },
  {
    item: "Hedera",
    slug: "hedera",
    placeholder: "Wallet address",
    coin: "HBAR",
    id: "",
    startDate: "2019-09-20",
  },
  {
    item: "Klaytn",
    slug: "klaytn",
    placeholder: "0x... address",
    coin: "KLAY",
    id: 8217,
    startDate: "2020-03-31",
  },
  {
    item: "Moonbeam",
    slug: "moonbeam",
    placeholder: "0x... address",
    coin: "GLMR",
    id: 1284,
    startDate: "2022-01-11",
  },
  {
    item: "Near",
    slug: "near",
    placeholder: "Wallet address",
    coin: "NEAR",
    id: "",
    startDate: "2020-10-14",
  },
  {
    item: "Polygon",
    slug: "polygon",
    placeholder: "0x... address",
    coin: "MATIC",
    id: 137,
    startDate: "2019-04-29",
  },
  {
    item: "Ripple",
    slug: "ripple",
    placeholder: "r... address",
    coin: "XRP",
    id: "",
    startDate: "2013-08-05",
  },
  {
    item: "Solana",
    slug: "solana",
    placeholder: "Wallet address",
    coin: "SOL",
    id: "",
    startDate: "2020-04-11",
  },
  {
    item: "Tron",
    slug: "tron",
    placeholder: "0x... address",
    coin: "TRX",
    id: "",
    startDate: "2017-09-14",
  },
];

export default blockchains;
