export const blockchains = [
  {
    item: "Aeternity",
    slug: "aeternity",
    placeholder: "ak_... address",
    coin: "AE",
    id: "",
  },
  {
    item: "Binance",
    slug: "bsc",
    placeholder: "0x... address",
    coin: "BNB",
    id: 56,
  },
  {
    item: "Celo",
    slug: "celo",
    placeholder: "0x... address",
    coin: "CELO",
    id: 42220,
  },
  {
    item: "Cube",
    slug: "cube",
    placeholder: "0x... address",
    coin: "CUBE",
    id: 1818,
  },
  {
    item: "Ethereum",
    slug: "ethereum",
    placeholder: "0x... or .eth",
    coin: "ETH",
    id: 1,
  },
  {
    item: "Evmos",
    slug: "evmos",
    placeholder: "0x... address",
    coin: "EVMOS",
    id: 9001,
  },
  {
    item: "Hedera",
    slug: "hedera",
    placeholder: "Wallet address",
    coin: "HBAR",
    id: "",
  },
  {
    item: "Klaytn",
    slug: "klaytn",
    placeholder: "0x... address",
    coin: "KLAY",
    id: 8217,
  },
  {
    item: "Moonbeam",
    slug: "moonbeam",
    placeholder: "0x... address",
    coin: "GLMR",
    id: 1284,
  },
  {
    item: "Near",
    slug: "near",
    placeholder: "Wallet address",
    coin: "NEAR",
    id: "",
  },
  {
    item: "Polygon",
    slug: "polygon",
    placeholder: "0x... address",
    coin: "MATIC",
    id: 137,
  },
  {
    item: "Ripple",
    slug: "ripple",
    placeholder: "r... address",
    coin: "XRP",
    id: "",
  },
  {
    item: "Solana",
    slug: "solana",
    placeholder: "Wallet address",
    coin: "SOL",
    id: "",
  },
  {
    item: "Tron",
    slug: "tron",
    placeholder: "0x... address",
    coin: "TRX",
    id: "",
  },
];
